---
title: "Lecture Slides"
---

## Lectures (1/2) {.smaller}

::: {.nonincremental}
1. [Lecture 01: Introduction - A Roadmap to Autonomous Robotic Systems](01-introduction-to-robotics.qmd)
2. [Lecture 02: Robot Modeling I - Rigid Body Motions](02-mathematical-foundations-se3.qmd)
3. [Lecture 03: Robot Modeling II - Forward Kinematics](05-robot-modeling-1-kinematics.qmd)
4. [Lecture 04: Robot Modeling III - Velocity Kinematics and Inverse Kinematics](06-robot-modeling-2-velocity-jacobians.qmd)
5. [Lecture 05: Robot Modeling IV - Dynamics of Open Chains](07-robot-modeling-3-dynamics.qmd)
6. [Lecture 06: Robot Simulation - Modern Physics Engines and Contact Dynamics](08-robot-simulation.qmd)
7. [Lecture 07: Actuation I - Electric Motors, Transmissions, and Torque Generation](13-actuation-1-motors-transmissions-torque.qmd)
8. [Lecture 08: Actuation II - Actuator Dynamics and Low-Level Control](14-actuation-2-actuator-dynamics-low-level-control.qmd)
:::

## Lectures (2/2) {.smaller}

::: {.nonincremental}
9. [Lecture 09: Planning - Trajectory Generation and Motion Planning](09-motion-planning.qmd)
10. [Lecture 10: Control I - Computed Torque Control](10-control-1-pid-basics.qmd)
11. [Lecture 11: Control II - Operational-Space Control](11-control-2-operational-space-control.qmd)
12. [Lecture 12: Reactive Control - Potential Fields, Velocity Fields, and Model Predictive Control](12-reactive-control.qmd)
13. [Lecture 13: Perception I - Sensors, Measurements, Noise, and State Estimation](03-perception-1-sensors-noise-state-estimation.qmd)
14. [Lecture 14: Perception II - Camera Modeling and Calibration](04-perception-2-rgbd-object-pose-estimation.qmd)
15. [Lecture 15: A Brief Introduction to Learning-Based Robot Control](16-integrated-robotic-systems.qmd)
:::
