---
title: "Lecture Notes"
---

## Lectures

### Introduction
1. [Lecture 01: Introduction - A Roadmap to Autonomous Robotic Systems](01-introduction-to-robotics.qmd)

### Robot Modeling
2. [Lecture 02: Robot Modeling I - Rigid Body Motions](04-robot-modeling-1-rigid-body-motions.qmd)
3. [Lecture 03: Robot Modeling II - Forward Kinematics](05-robot-modeling-2-forward-kinematics.qmd)
4. [Lecture 04: Robot Modeling III - Velocity Kinematics and Inverse Kinematics](06-robot-modeling-3-velocity-kinematics-inverse-kinematics.qmd)
5. [Lecture 05: Robot Modeling IV - Dynamics of Open Chains](07-robot-modeling-4-dynamics-open-chains.qmd)
6. [Lecture 06: Robot Simulation - Modern Physics Engines and Contact Dynamics](08-robot-simulation-modern-physics-engines-contact-dynamics.qmd)

### Actuation
7. [Lecture 07: Actuation I - Electric Motors, Transmissions, and Torque Generation](02-actuation-1-motors-transmissions-torque.qmd)
8. [Lecture 08: Actuation II - Actuator Dynamics and Low-Level Control](03-actuation-2-actuator-dynamics-low-level-control.qmd)

### Planning and Control
9. [Lecture 09: Planning - Trajectory Generation and Motion Planning](09-planning-trajectory-generation-motion-planning.qmd)
10. [Lecture 10: Control I - Computed Torque Control](10-control-1-pid-and-computed-torque.qmd)
11. [Lecture 11: Control II - Operational-Space Control](11-control-2-operational-space-control.qmd)
12. [Lecture 12: Reactive Control - Potential Fields, Velocity Fields, and Model Predictive Control](12-reactive-control-potential-fields-velocity-fields-mpc.qmd)

### Perception
13. [Lecture 13: Perception I - Sensors, Measurements, Noise, and State Estimation](13-perception-1-sensors-noise-state-estimation.qmd)
14. [Lecture 14: Perception II - Camera Modeling and Calibration](14-perception-2-camera-modeling-calibration.qmd)

### Introduction to Learning-based Robot Control
15. [Lecture 15: A Brief Introduction to Robot Learning](16-integrated-robotics-from-perception-to-action.qmd)
